### ISSUE TITLE
Barcelona unable to read local image paths from received attachments on iOS

### ISSUE THREAD

**Issue by CarlAmbroselli** [open-imcore/barcelona#38]
This is a follow-up after fixing the crash from #35.

The following happens when receiving an image on iOS:

```
[Feb 17, 2022 09:14:38] [iMessage/Mac-noSIP/IPC/DEBUG] Received IPC command: message/0
[Feb 17, 2022 09:14:38] [Portal/iMessage;-;+1111222333/DEBUG] Starting handling of iMessage 283CFA7E-ECA7-4EC2-A07E-2A3DA0B816E1
[Feb 17, 2022 09:14:38] [Portal/iMessage;-;+1111222333/ERROR] Failed to read attachment in 283CFA7E-ECA7-4EC2-A07E-2A3DA0B816E1: open /var/root/Library/SMS/Attachments/15/05/2563A808-F4F9-4368-908D-2B8633D71131/D4BD1DD5-EC6B-49FA-B5B0-938359C44A59.jpeg: no such file or directory
[Feb 17, 2022 09:14:38] [Portal/iMessage;-;+1111222333/ERROR] Panic while handling 283CFA7E-ECA7-4EC2-A07E-2A3DA0B816E1: assignment to entry in nil map
goroutine 76 [running]:
runtime/debug.Stack()
        /opt/homebrew/Cellar/go/1.17.6/libexec/src/runtime/debug/stack.go:24 +0x88
main.(*Portal).HandleiMessage.func1(0x130464900, 0x13002a480)
        /Users/ci/builds/YUMeaPfZ/0/mautrix/imessage/portal.go:1276 +0x48
panic({0x100917f40, 0x10099e470})
        /opt/homebrew/Cellar/go/1.17.6/libexec/src/runtime/panic.go:1038 +0x21c
main.(*Portal).sendMessage(0x130464900, 0x1304342c0, {{0x100780ffd, 0xe}, 0x1}, {0x1009629c0, 0x130128000}, 0x0, 0x17f06f641e7)
        /Users/ci/builds/YUMeaPfZ/0/mautrix/imessage/portal.go:721 +0x108
main.(*Portal).handleIMAttachments(0x130464900, 0x13002a480, 0x130065ea8, 0x1304342c0)
        /Users/ci/builds/YUMeaPfZ/0/mautrix/imessage/portal.go:1186 +0x1d8
main.(*Portal).HandleiMessage(0x130464900, 0x13002a480, 0x0)
        /Users/ci/builds/YUMeaPfZ/0/mautrix/imessage/portal.go:1304 +0x418
main.(*Portal).handleMessageLoop(0x130464900)
        /Users/ci/builds/YUMeaPfZ/0/mautrix/imessage/portal.go:341 +0x108
created by main.(*Bridge).NewPortal
        /Users/ci/builds/YUMeaPfZ/0/mautrix/imessage/portal.go:161 +0x2dc
[Feb 17, 2022 09:14:40] [iMessage/Barcelona/IMDPersistenceQueries/DEBUG] loading 1 guids
[Feb 17, 2022 09:14:40] [iMessage/Barcelona/IMDPersistenceQueries/DEBUG] loaded 1 guids
[Feb 17, 2022 09:14:40] [iMessage/Barcelona/IMDPersistenceQueries/DEBUG] converting 1 refs
[Feb 17, 2022 09:14:40] [iMessage/Barcelona/BLStandardIO/INFO] Outgoing! message -1
[Feb 17, 2022 09:14:40] [iMessage/Mac-noSIP/IPC/DEBUG] Received IPC command: message/0
[Feb 17, 2022 09:14:40] [Portal/iMessage;-;+1111222333/DEBUG] Starting handling of iMessage 30884228-9F66-4A87-BDF1-DE7545E794F1
[Feb 17, 2022 09:14:40] [Portal/iMessage;-;+1111222333/ERROR] Failed to read attachment in 30884228-9F66-4A87-BDF1-DE7545E794F1: open /var/root/Library/SMS/Attachments/15/05/2563A808-F4F9-4368-908D-2B8633D71131/D4BD1DD5-EC6B-49FA-B5B0-938359C44A59.jpeg: no such file or directory
```

This image actually exists under `/private/var/mobile/Library/SMS/Attachments/15/05/2563A808-F4F9-4368-908D-2B8633D71131/D4BD1DD5-EC6B-49FA-B5B0-938359C44A59.jpeg`

**Comment by CarlAmbroselli** [comment]
This can be fixed by running the following on the iPhone:
```
ln -s /private/var/mobile/Library/SMS /var/root/Library/SMS
```

**Comment by CarlAmbroselli** [comment]
Updated the instructions to fix this in https://github.com/open-imcore/barcelona/pull/36, closing out here.
